plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.example.bettercombatfix'
version = '1.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('run')

            mods {
                bettercombatfix {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()

    maven {
        url = 'https://maven.minecraftforge.net'
    }

    maven {
        url 'https://api.modrinth.com/maven'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'

    implementation fg.deobf('maven.modrinth:better-combat:1.9.0+1.20.1-forge')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar.finalizedBy('reobfJar')